### ISSUE TITLE
Device Edits and Update Status Broken?

### ISSUE THREAD

**Issue by JBBBB** [jokob-sk/Pi.Alert#509] opened 2023-11-20 10:19 UTC
First, thank you for this app.  It looks promising.  I just created the container today, so I haven't had much time with it yet.

So far, the Arp-Scan and Pholus-Scan found all devices (67 of them) on my network (5 subnets) and resolved hostnames as expected. Most "devices" are Docker Containers and Proxmox VMs.

Unfortunately, I've run into two frustrating issues with editing devices. I may be missing something, but...  

1. **_Is it possible to speed up the process of updating the devices list after editing a device's info?_** When editing device info, the changes take forever to appear in the devices list.  It kills the workflow of managing device info because it makes it difficult to keep track of changes made and requires editing the same device multiple times.  It is torturous.  
2.  **_Can the Vendor field be blank?_** I started setting these to blank for VMs and Docker containers; however, after some time the field resets automatically back to **(Unknown: locally administered)**.  I also tried setting it to just a "-", but nope.  It again was set back to  **(Unknown: locally administered)**.  These words have no value and only add clutter to the table. 

Also, the Maintenance menu title is tagged with **NEW**, and the App updates Status indicates that a new version is available.  I just pulled the image earlier today.  I even deleted the container and earlier image, and then pulled the latest image again, but the status still indicates that a newer version is available.  Is there an easy way to disable this? If not, there should be.

**Comment by jokob-sk** [comment] 2023-11-20 21:37
Hi there,

Thanks for using this app!

1. There seems to be a bug not allowing you to cycle between devices once on a device with the arrows in the top right corner. That would mean you don't have to go to the devices listing page after editing a device. The refresh rate is given by the API endpoints expiration / update and not easily changed. I'm considering adding a loading overlay until newest data is fetched in the future, but low priority right now. Will have a look at the arrows not working properly though. You can bulk edit devices via the CSV approach in the mean time: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEVICES_BULK_EDITING.md
2. You can hide columns you don't want to show in the Maintenance page or add a fake vendor of your choosing (e.g.: none) which should prevent it to go back and try to rediscover the vendor.
3. There might be a version check bug. Will look into this to try to reproduce it on my end.

Thanks,
J

**Comment by JBBBB** [comment] 2023-11-22 05:21
Thank you for the reply...

1. My concern is the lag time between:  a) saving the changes when editing a device, and b) when these changes appear in the device list.   This lag time can be several minutes even after pressing the recycle/refresh button.   I presume the changes are written to the SQLite database and then device list reads this database.  It shouldn't take minutes.  The bulk edit was a great help though.  I was able to easily clean up results from the initial scan and then import them - nice.
2. I tried adding fake vendors (ie. changing content of the **Vendor** field), but they keep getting overwritten.  I also have unchecked **New Device** hoping it may keep the device from being updated, but that doesn't seem to work.   I don't like  **(Unknown: locally administered)**, but I'll live with it.
3. Thanks.

**Comment by jokob-sk** [comment] 2023-11-22 08:03
Hi there,

1. As mentioned, the list view depends on the API endpoints being updated, it doesn't read from the DB directly. Fixed the cycling thru the devices so you don't have to go to the Devices list view anymore to quickly edit multiple devices:
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/08c4c53e-f940-4970-b92b-313c3822497d). 

I'll look into the number 2 & 3 issues later on.

**Comment by jokob-sk** [comment] 2023-11-22 08:23
2. Vendor overwrite should be now prevented once the vendor is set to a non-empty value.

**Comment by jokob-sk** [comment] 2023-11-22 08:32
3. I can't seem to be able to reproduce the Update check issue. I pulled the latest docker image and the update check seems to be correctly indicating that I'm on the latest version: 
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/451022b0-75b8-4978-81cd-4a3fa593b8d9)

**Comment by JBBBB** [comment] 2023-11-22 23:45
1. and 2.  Awesome! How do I access the fixes? Do I need to build my own image?

3. It's weird that you cannot reproduce this...  I: a) deleted the container and images, b) deleted all files in the volumes, and c) then pulled latest and recreated the container.   I am still seeing "A new version is available".

**Comment by jokob-sk** [comment] 2023-11-23 00:14
Hey!

1. Check the bottom of this issue if you want to test the dev image: https://github.com/jokob-sk/Pi.Alert/issues/138
2. Weird - in general I'd get tons of reports if this wouldn't be working - happened in the past - so I'm leaning towards an environment/caching issue. Here is a bit of background how the version check works - might help to debug it: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/VERSIONS.md

**Comment by hobybrenner** [comment] 2023-11-23 14:06
I see the same issue with New version available as well on a new install here.

**Comment by mscreations** [comment] 2023-11-28 23:12
I too am seeing the version issue on my existing install. It appears that no matter what, during start.sh execution, the command 'date +%s' on my system seems to generate the buildtimestamp of 1699667486. I've tried deleting that file explicitly and after a restart, buildtimestamp.txt contains that date again. 

After a bit more looking, I found that I had inadvertently set a TZ environment variable of 'America/New_York' in my container. After removing the environment variable, my install is now properly showing that I'm up to date. My best guess is that it is converting one of the timestamps into the time zone and the other is not being converted but then they are being compared. I think this is causing the mismatch and failure. Again, I'm not positive if this is the actual issue, but after removing that environment variable and restarting, I am properly getting the message that I'm up to date.

**Comment by jokob-sk** [comment] 2023-11-29 00:26
thanks everyone for confirmation - I've been a bit flat out IRL and @mscreations tried to fix this, so you can check the `_dev` image after the build finishes if interested - thanks in advance 🙏

**Comment by JBBBB** [comment] 2023-11-29 04:31
Ahhh...  I also was setting TZ=America/New_York through an **--env** argument in docker run.   I removed it and the new version issue went away as well.  Good work, Jon!

**Comment by ajtatum** [comment] 2023-12-16 00:49
The devices not updating is a real PITA. I even exported devices, edited them, and then imported them and the changes didn't take affect. The only way I can seem to force it is by restarting the container. This is definitely an issue with this fork, as I tried out https://github.com/leiweibau/Pi.Alert and after I edit a device and go back to the Devices screen, the edit shows up immediately.

**Comment by ajtatum** [comment] 2023-12-16 03:54
It's quite strange how similar and yet far apart your repo is compared to https://github.com/leiweibau/Pi.Alert. There is a mixture of more/less functionality in both repos; however, yours has more functionality overall and has a nicer UI; but the other repo seems to be, thus far, more stable. The features that are there work without any issues. I miss your repo with the nicer UI and network topology, but I have to take the reliable route. Hopefully, perhaps, you guys can work together...

**Comment by jokob-sk** [comment] 2023-12-16 04:05
@ajtatum It's impossible to merge these forks as the development approach is too different. 

With more functionality come more edge cases which I will address over time. I will have a look how to refresh the devices or implement a wait until the screen is populated with new data.

**Comment by jokob-sk** [comment] 2023-12-16 05:34
@ajtatum @JBBBB The devices view will have a refresh spinner until the new data is loaded (2-3s):

 
![record-16 29 25 16 12 2023](https://github.com/jokob-sk/Pi.Alert/assets/96159884/dbbbfe6b-9cfd-4f27-824c-18c58c10cef9)

**Comment by jokob-sk** [comment] 2023-12-16 09:50
closing as released 🚀

**Closed by jokob-sk** 2023-12-16 09:50 UTC
Labels: bug 🐛, next release/in dev image🚀
