### ISSUE TITLE
New version is broken?

### ISSUE THREAD

**Issue by viriatusX** [jokob-sk/Pi.Alert#112] opened 2022-12-08 17:45 UTC
Good afternoon,
since the last update, docker is constantly restarting. It does not work. what could it be?

My docker-compose: 
----------------------
version: '3.5'

services:
  
  pialert:
    container_name: pialert
    image: jokobsk/pi.alert:latest
    volumes:
     - /volume4/docker/pialert/config:/home/pi/pialert/config
     - /volume4/docker/pihole-unbound/pihole-configs/pihole-FTL.db:/home/pi/pialert/pihole-FTL.db:ro
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
      - USER_ID=1024
      - USER_GID=100
      - 
    restart: unless-stopped
    network_mode: host

volumes:
  pialert_db: 
    external: true

---------------------

<img width="1450" alt="Captura de Pantalla 2022-12-08 a las 18 43 32" src="https://user-images.githubusercontent.com/64467637/206525116-3eefc364-df70-4f65-976a-f84d1def980b.png">

**Comment by mrulke** [comment] 2022-12-08 22:26
yeah im having the same issue

**Comment by jokob-sk** [comment] 2022-12-09 07:59
Hi there!

I rewrote a big chunk of the code, so bugs are possible and I expected some, so thanks for raising the issue. 

- The old approach relied on CRON, so even if something failed or didn't work, the application seemed to work OK
- The new approach relies on a loop, and thus if the app crashed, the image crashes as well

I'm running the container for a week without issues, but I don't use the pihole integration. 

@mrulke Are you using a pihole DB? I f yes, I can try it on my end. 

Otherwise, can you have a look at the logs to see if there are any relevant errors? 

@viriatusX Can you try mounting the DB file directly just for testing?

You can map the log folder as per Example 1:

https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-1

I can build a DEV image with more debugging output, but let's see if we can find something on this one. 

Thanks in advance for the help!
j

**Comment by faileador1** [comment] 2022-12-10 10:51
As described in first post.

Two NAS with same config, updated one is not working, constantly restarting pialert container.

**Comment by jokob-sk** [comment] 2022-12-10 11:52
Hi @faileador1 ,

As per above, can you please provide me more details?

> Otherwise, can you have a look at the logs to see if there are any relevant errors?
> Are you using pihole?

You can map the log folder as per Example 1:

https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-1

Cheers in advance!
j

**Comment by viriatusX** [comment] 2022-12-10 11:57
> Hi @faileador1 ,
> 
> As per above, can you please provide me more details?
> 
> > Otherwise, can you have a look at the logs to see if there are any relevant errors?
> > Are you using pihole?
> 
> You can map the log folder as per Example 1:
> 
> https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-1
> 
> Cheers in advance! j

Hi!
This show my log:

Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 51, in <module>
    exec(open(PIALERT_PATH + "/config/pialert.conf").read())
  File "<string>", line 21, in <module>
NameError: name 'SMTP_USER' is not defined


Thanks!!

**Comment by faileador1** [comment] 2022-12-10 12:55
> Hi @faileador1 ,
> 
> As per above, can you please provide me more details?
> 
> > Otherwise, can you have a look at the logs to see if there are any relevant errors?
> > Are you using pihole?
> 
> You can map the log folder as per Example 1:
> 
> https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-1
> 
> Cheers in advance! j

`#=#=#                                                                         
##O#-#                                                                        
##O=#  #                                                                      
#=#=-#  #                                                                     

                                                                           0.4%
#######                                                                    9.8%
###############################                                           43.9%
#####################################################                     74.4%
######################################################################## 100.0%
#=#=#                                                                         
##O#-#                                                                        
##O=#  #                                                                      

                                                                           0.1%
#                                                                          1.5%
####                                                                       6.6%
########                                                                  11.6%
############                                                              16.9%
###############                                                           22.2%
###################                                                       27.5%
#######################                                                   32.9%
###########################                                               38.3%
###############################                                           43.6%
###################################                                       49.0%
#######################################                                   54.4%
##########################################                                59.7%
##############################################                            64.1%
##################################################                        70.0%
######################################################                    75.4%
#########################################################                 80.1%
#############################################################             86.1%
#################################################################         91.4%
#####################################################################     96.6%
######################################################################## 100.0%
#=#=#                                                                         
##O#-#                                                                        
##O=#  #                                                                      

                                                                           0.3%
#####                                                                      7.5%
#########                                                                 13.2%
###########                                                               16.1%
##############                                                            20.4%
##################                                                        25.3%
#####################                                                     30.5%
##########################                                                37.1%
#############################                                             40.4%
#################################                                         46.9%
######################################                                    53.5%
###########################################                               60.0%
#############################################                             63.3%
##################################################                        69.9%
####################################################                      73.1%
#########################################################                 79.7%
##########################################################                81.8%
###############################################################           88.3%
####################################################################      94.9%
######################################################################## 100.0%
#=#=#                                                                         
##O#-#                                                                        

                                                                           0.2%
###                                                                        4.4%
#####                                                                      7.6%
######                                                                     9.3%
########                                                                  11.2%
#########                                                                 13.6%
###########                                                               15.4%
############                                                              17.6%
##############                                                            20.4%
#################                                                         24.3%
##################                                                        26.2%
#####################                                                     30.1%
#######################                                                   32.0%
########################                                                  33.9%
###########################                                               37.8%
############################                                              39.7%
###############################                                           43.6%
################################                                          45.5%
###################################                                       48.6%
#####################################                                     52.5%
#######################################                                   54.4%
#########################################                                 58.3%
############################################                              62.1%
##############################################                            64.1%
###############################################                           66.0%
###################################################                       71.8%
#####################################################                     73.7%
#######################################################                   77.6%
##########################################################                81.4%
#############################################################             85.3%
################################################################          89.1%
##################################################################        93.0%
#######################################################################   98.8%
######################################################################## 100.0%
#=#=#                                                                         
##O#-#                                                                        
##O=#  #                                                                      
#=#=-#  #                                                                     

                                                                           0.3%
#####                                                                      7.9%
##########                                                                14.0%
############                                                              17.1%
##############                                                            20.4%
#################                                                         24.1%
####################                                                      28.3%
#######################                                                   32.0%
###########################                                               37.6%
#############################                                             41.0%
##################################                                        48.0%
#####################################                                     51.4%
##########################################                                58.4%
############################################                              61.8%
#################################################                         68.8%
######################################################                    75.7%
########################################################                  79.2%
#############################################################             86.1%
################################################################          90.3%
###################################################################       93.7%
######################################################################## 100.0%
`

**Comment by mrulke** [comment] 2022-12-10 23:32
I am using pi hole but have not set it up in pi alert.

**Comment by jokob-sk** [comment] 2022-12-10 23:49
@viriatusX 

Thanks for that!

That means that even previously, PiAlert probably wasn't working properly. Now the difference is that at least it fails, so you notice it's not working. If you don't use email reporting (I assume you don't since you don't have `SMTP_USER` defined), set `REPORT_MAIL             = False` in your `pialert.conf` file. 

I'm looking into making the error logs more accessible and logging a bit more cleaner to debug your issue @faileador1  as well. 

Will get back once I have a new image for you to test.

@mrulke Do you have anything relevant in your logs?

Thanks in advance,
j

**Comment by mrulke** [comment] 2022-12-10 23:59
No that I can see I'll try again tonight.

**Comment by viriatusX** [comment] 2022-12-11 00:08
> @viriatusX
> 
> ¡Gracias por eso!
> 
> That means that even previously, PiAlert probably wasn't working properly. Now the difference is that at least it fails, so you notice it's not working. If you don't use email reporting (I assume you don't since you don't have `SMTP_USER` defined), set `REPORT_MAIL = False` in your `pialert.conf` file.
> 
> I'm looking into making the error logs more accessible and logging a bit more cleaner to debug your issue @faileador1 as well.
> 
> Volveré cuando tenga una nueva imagen para que la pruebes.
> 
> @mrulke¿Tienes algo relevante en tus registros?
> 
> Gracias de antemano,julio

That's the strange thing. I have an email defined in SMTP_USER but I have it configured REPORT_MAIL = False.

I don't understand the error then...

**Comment by jokob-sk** [comment] 2022-12-11 00:41
@viriatusX 

Great, we are making progress!

How did you set your `SCAN_SUBNETS` variable?

**Comment by jokob-sk** [comment] 2022-12-11 11:41
In the latest image:

I've built a crude Logs section and made sure the logs are updated more frequently than before. This might help you to debug your issues easier.

![image](https://user-images.githubusercontent.com/96159884/206901403-52f4ce32-5abc-491e-98bc-a2be603860fb.png)

Please note, I had to move the logs location form:

- `home/pi/pialert/log`

to

- `home/pi/pialert/front/log`

So change your docker-compose mappings if needed.

**Comment by mrulke** [comment] 2022-12-12 02:59
Looks like it is working for me now. Added my extra networks as well.
Awesome stuff

**Comment by danktankk** [comment] 2022-12-13 03:38
I am also having issue with getting this to see VLANS.  Im not sure its related to the version however.  I am still testing.

**Comment by jokob-sk** [comment] 2022-12-13 08:04
Hi @danktankk ,

Can you post your docker-compose? I'm not sure what multiple VLANS are, but to scan multiple interfaces use this approach:

   * Examples for one and two subnets:
     * `SCAN_SUBNETS    = '192.168.1.0/24 --interface=eth0'`
     * `SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0', '192.168.1.0/24 --interface=eth1']`

AFAIK you need to have access to piholes DB to use it, so they need to be installed on the same HW or at least made available via a mount in the PiAlert container. I myself am not using pihole so can't comment on this approach in more detail.

If the README is not specific enough, please do let me know how to improve it.

Thanks,
j

**Comment by mrulke** [comment] 2022-12-13 08:09
I am using an interface on each vlan as it uses arp to find devices and you can't arp cross subnets.



________________________________

**Comment by danktankk** [comment] 2022-12-15 04:35
> I am using an interface on each vlan as it uses arp to find devices and you can't arp cross subnets.
> […](#)

Thats what I was afraid of as ARP is layer 2.  I ahve read about a few different implementations where it will traverse layer 3, but im afraid my pay grade isnt high enough to implement that.   I have 5 VLANS so I guess that means I will need to add in 5 vnetwork cards to my VM to see this traffic :\..  ergggg

Or..  Perhaps.... An easier way might be using my pihole rpi3?  How would I map my pihole that lives on the same network as this VM?

I have the VM running ubuntu server on 192.168.1.0/24 network - add pihole running on same 192.168.1.0/24 network

This PiHole can see the other VLANS already.  Is there a way (I dont particularly care if its easy) to add this pihole to the pialert.conf file on my VM?  Ill admit I have tried a few times without success.

**Comment by danktankk** [comment] 2022-12-15 04:50
> Hi @danktankk ,
> 
> Can you post your docker-compose? I'm not sure what multiple VLANS are, but to scan multiple interfaces use this approach:
> 
> * Examples for one and two subnets:
>   
>   * `SCAN_SUBNETS    = '192.168.1.0/24 --interface=eth0'`
>   * `SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0', '192.168.1.0/24 --interface=eth1']`
> 
> AFAIK you need to have access to piholes DB to use it, so they need to be installed on the same HW or at least made available via a mount in the PiAlert container. I myself am not using pihole so can't comment on this approach in more detail.
> 
> If the README is not specific enough, please do let me know how to improve it.
> 
> Thanks, j

Thank you for the reply...  Multiple VLANS simply means you are using network hardware capable of separating network traffic for a variety of reasons (managed vs unmanaged switches).  The reason for VLANS here isn't particularly important (i.e. security, segregation, minimalization, control, automation, IoT, NoT, etc), but needs mention due to this implementation using a layer 2 protocol - ARP - as the main way to poll devices.

If you implement a solution that uses layer 2, then you literally will need a dedicated NIC to poll each VLAN (Virtual Local Area Network) that also goes through a managed switch (which is not surprising at all).  In the case of a VM, you could in practice add multiple nics virtually to do this job.  I do not like this solution however as I have too many VLANS for this to be feasable.

I guess my only alternative would be to map the pihole to my VM and then somehow tell it to look there....  

i am better at networking than I am at linuxing....  :|

So, for anyone that cares to help..  I have an ESXi 8 VM Ubuntu Server 22.04 that I will need to mount the pihole db share to.  This is probably easy for the raspbian, debain, or slackware aficionado.  I will then have to tell the conf where to look as well.  Any help is most appreciated.

**Comment by viriatusX** [comment] 2022-12-16 10:41
Sorry for my late response @jokob-sk .
I just updated to the latest version.
I have an old pialert.conf file. On the new file, i not just see the Pi.alert DB path. 
<img width="1083" alt="Captura de Pantalla 2022-12-16 a las 11 39 58" src="https://user-images.githubusercontent.com/64467637/208080690-0c53b15f-8d51-4a29-bab2-66315a7761ad.png">

MY CURRENT LOG
----------------------



Loop start
---------------------------
Check Internet IP
    Timestamp:2022-12-16 11:38:00

    Retrieving Internet IP...
   83.44.242.190

    Retrieving previous IP...
   83.44.242.190
    No changes to perform

    Skipping Dynamic DNS update...
Scan Devices
    ScanCycle:1
    Timestamp:2022-12-16 11:38:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......:8
        arp-scan Method....:6
        Pi-hole Method.....: +0
        New Devices........: 0

    Devices in this cycle..: 8
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 6
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...

        Names updated:  0
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Check if something to report...
    No changes to report...
    Notifications:6
Cleanup Database
    Timestamp:2022-12-16 11:38:00
    Cleanup Online_History...
    Optimize Database...
    Cleanup Events, up to the lastest 90 days...
    Shrink Database...

Finished cycle: cleanup


Loop end
---------------------------

 Wait 20s

 Wait 20s

Loop start
---------------------------

Loop end
---------------------------

 Wait 20s



-----------------------------------

**Comment by jokob-sk** [comment] 2022-12-16 22:11
Hey @viriatusX !

Looks like the backend works fine now, which is great. I think your DB should be updated correctly. 

Now I think the issue is that the `pialert.db` doesn't have correct permissions. I think the nginx user doesn't have RW permissions on the DB file.  You can try to go nuclear and run `chmod +777 pialert.db` on your host or/and in the container. 

You can also check the dev tools in chrome/firefox (F12) if you can see any errors, but I think it's the DB permissions thing. 

Thanks,
j

**Comment by jokob-sk** [comment] 2022-12-16 22:17
Hi @danktankk,

Not sure if I'll be able to help with network related stuff.  Layer 2 etc talk is a bit more than what I'm familiar with.  If you have pihole working, then that might be a workaround. Check the sample `pialert.conf` and use the relevant PiHole settings. 

An alternative, if you by any chance use Home Assistant, and if you get PiAlert working on all VLANS, you can use Home Assistant as your 'hub'. You point all PiAlert instances to one Home Assistant (HA) instance and use the MQTT integration to sync the devices into HA.

j

**Comment by viriatusX** [comment] 2022-12-16 23:19
> Hey @viriatusX !
> 
> Looks like the backend works fine now, which is great. I think your DB should be updated correctly.
> 
> Now I think the issue is that the `pialert.db` doesn't have correct permissions. I think the nginx user doesn't have RW permissions on the DB file. You can try to go nuclear and run `chmod +777 pialert.db` on your host or/and in the container.
> 
> You can also check the dev tools in chrome/firefox (F12) if you can see any errors, but I think it's the DB permissions thing.
> 
> Thanks, j

<img width="1464" alt="Captura de pantalla 2022-12-17 a las 0 17 59" src="https://user-images.githubusercontent.com/64467637/208204086-62eb4be0-47b4-457e-a4d5-d2042d82b83e.png">

Hi!
I checked and the paler.db is set to 777.
ANd I not see any errors with firefox.

**Comment by jokob-sk** [comment] 2022-12-16 23:29
Can you please try rebuilding / redownloading the image?

**Comment by viriatusX** [comment] 2022-12-16 23:39
> Can you please try rebuilding / redownloading the image?
> […](#)
Yes, look the log.
there is a problem with "mkdir: cannot create directory '/run/php': File exists".
this problem is shown in the log, since the version that started to go wrong.

<img width="783" alt="Captura de pantalla 2022-12-17 a las 0 37 48" src="https://user-images.githubusercontent.com/64467637/208208217-422eca64-6aea-4947-8bac-886961d1d963.png">

**Comment by jokob-sk** [comment] 2022-12-16 23:50
I think that's a common warning and not related to the problem. I can
however see that your subnets variable is not configured correctly.

You seem to use eth1 which doesn't exist on your server. Can you please
look into this?

**Comment by viriatusX** [comment] 2022-12-17 00:02
Could this be the problem? How do I change the "eth1" interface? In my case I use Link Aggregation on the Synology and the web interface is "bond0". 

<img width="554" alt="Captura de pantalla 2022-12-17 a las 1 01 13" src="https://user-images.githubusercontent.com/64467637/208210556-63dcecfc-a607-40c7-bb67-7a18314b3214.png">

**Comment by viriatusX** [comment] 2022-12-17 00:06
UPDATE:

    Skipping Dynamic DNS update...
Scan Devices
    ScanCycle:1
    Timestamp:2022-12-17 01:05:00

Scanning...
    arp-scan Method...
    arp-scan: One interface
sudo: unable to resolve host pialert: Name or service not known

    Pi-hole Method...
    DHCP Leases Method...

Processing scan results...
    Devices Detected.......:21
        arp-scan Method....:19
        Pi-hole Method.....: +0
        New Devices........: 14

    Devices in this cycle..: 7
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 0
        Disconnections.....: 0
        IP Changes.........: 0

Updating DB Info...
    Sessions Events (connect / discconnect) ...
    Creating new devices...
    Updating Devices Info...
        Trying to resolve devices without name...

        Names updated:  7
    Voiding false (ghost) disconnections...
    Pairing session events (connection / disconnection) ...
    Creating sessions snapshot...
    Skipping repeated notifications...

Check if something to report...

Changes detected, sending reports...
    Skip mail...
    Skip Apprise...
    Skip webhook...
    Skip NTFY...
    Skip PUSHSAFER...
    Skip MQTT...
    Notifications:14
Cleanup Database
    Timestamp:2022-12-17 01:05:00
    Cleanup Online_History...
    Optimize Database...
    Cleanup Events, up to the lastest 90 days...
    Shrink Database...

Finished cycle: cleanup


Loop end
---------------------------

 Wait 20s

**Comment by jokob-sk** [comment] 2022-12-17 00:20
Great, getting there.

Can you confirm you run `chmod +777 pialert.db` inside of the container?
Not on the server.

**Comment by viriatusX** [comment] 2022-12-17 00:22
Yes, look:

<img width="707" alt="Captura de pantalla 2022-12-17 a las 1 22 13" src="https://user-images.githubusercontent.com/64467637/208212556-5f6568a5-2711-4f9d-9c77-40a865897159.png">

**Comment by jokob-sk** [comment] 2022-12-17 00:22
Also don't use '--localnet' but your actual network mask or how it is
called. Check the sample pialert.conf for examples.

**Comment by jokob-sk** [comment] 2022-12-17 01:07
One test which you can run is not to map the DB file in docker-compose. If everything loads with the default DB then it's almost certainly an issue with the permissions on your currently mapped DB file. 

Also, if you can share your current (without personal info) `pialert.conf` and 'docker-compose.yml' files so I can see the current state of things. 

> If I try to change settings in the web interface such as language, etc., and click "apply", no changes are applied.

This again seems to point to file access permission issues. Did you try to map your docker UID/GID to your servers? You can do it via the environment variables as described [here](https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#-recommended) and in [Example 1](https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-1).

**Comment by viriatusX** [comment] 2022-12-17 09:36
Without manually mapping the DB, now runs!!!!!. Is there any problem for not mapping the DB in the Compose? Thanks!!!

**Comment by danktankk** [comment] 2022-12-17 14:59
> Hi @danktankk,
> 
> Not sure if I'll be able to help with network related stuff. Layer 2 etc talk is a bit more than what I'm familiar with. If you have pihole working, then that might be a workaround. Check the sample `pialert.conf` and use the relevant PiHole settings.
> 
> An alternative, if you by any chance use Home Assistant, and if you get PiAlert working on all VLANS, you can use Home Assistant as your 'hub'. You point all PiAlert instances to one Home Assistant (HA) instance and use the MQTT integration to sync the devices into HA.
> 
> j

Thanks for the reply.  I dont know that I will be able to get this to work to see all of my network.  This layer 2 limitation is a killer.  I do have some alternatives that I could try i suppose.

I could install this on the actual raspberry pi (but I would rather not).

I could try using smb instead of nfs.  I have nfs set up and working so that pialert on my ubuntu server can see pihole-FTL.log, but it still doesnt populate any ip addresses other than the network in which pialert resides.  Im not sure if its a permissions issue or what.

Very frustrasting

**Comment by jonas740** [comment] 2022-12-17 19:00
i cant even get it to run although i followed all the instructions to the DOT!

Very strange way to set up a docker container from my point of view. 


`Loop start
---------------------------
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Loop start
---------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Loop start
---------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
Loop start
---------------------------
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Loop start
---------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Loop start
---------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
Loop start
---------------------------
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 170, in main
    upgradeDB()
  File "/home/pi/pialert/back/pialert.py", line 2099, in upgradeDB

    openDB()
  File "/home/pi/pialert/back/pialert.py", line 2173, in openDB
    sql_connection.execute('pragma journal_mode=wal') #
sqlite3.DatabaseError: file is not a database`

**Comment by jokob-sk** [comment] 2022-12-17 21:44
Hi @viriatusX ,

> Without manually mapping the DB, now runs!!!!!. Is there any problem for not mapping the DB in the Compose? Thanks!!!

Great, so as I thought, the issue are DB permissions,. I think you can get it working if you set the `HOST_USER_ID` and `HOST_USER_GID` env variables. If you use PiHole for that than theoretically it shouldn't matter too much, but any setting on the device itself managed in PiAlert will be lost. E..g. you'd lose your custom names of the devices if you use PiAlert to name them after a container rebuild. 

j

**Comment by jokob-sk** [comment] 2022-12-17 21:45
@jonas740 

Please make sure you map the DB file as per instructions. Seems like you are missing it. If the issue persists please open a new issue, this one is veering off-topic.

**Comment by jokob-sk** [comment] 2022-12-17 21:51
Hey @danktankk !

Yeah, sorry to leave you hanging, but I think that's as much advice I can give on networking related stuff. 

> I could try using smb instead of nfs. I have nfs set up and working so that pialert on my ubuntu server can see pihole-FTL.log, but it still doesnt populate any ip addresses other than the network in which pialert resides. Im not sure if its a permissions issue or what.

For testing try copying the below files manually to your server to make sure it's not network related.  

- `:/etc/pihole/dhcp.leases`
- `:/etc/pihole/pihole-FTL.db`

Hope this helps,
j

**Comment by danktankk** [comment] 2022-12-18 06:04
hehe ive installed this on the actual pihole server and it still doesnt work.  Looks like this needs more work.  Ill check back at some point

**Comment by jokob-sk** [comment] 2022-12-18 06:14
@danktankk I don't support direct installs on the HW, only docker deployments for this, but you can give this fork a go if interested: https://github.com/leiweibau/Pi.Alert/

I haven't seen your config files so maybe you are missing a setting. either way, feel free to try in the future - also please open a separate issue as this one is now a bit over-crowded with different support requests. 😉

**Comment by jokob-sk** [comment] 2022-12-18 06:17
I'm closing this as some issues have been fixed and it's a bit hard to keep track of everyone's setups and configurations. Feel free to open new issues if you are still facing problems and I will reply in the newly created issues.

**Closed by jokob-sk** 2022-12-18 06:17 UTC
Labels: Waiting for reply
