### ISSUE TITLE
 Device detail page has no information any more

### ISSUE THREAD

**Issue by pbek** [jokob-sk/Pi.Alert#195] opened 2023-03-11 15:33 UTC
Since the last docker image, I have #143 again.
The `getDeviceData` request has all the data it should present, but I get a JS error `Uncaught DOMException: The operation is insecure.` at `history.pushState(null, '', newRelativePathQuery);`.

![image](https://user-images.githubusercontent.com/1798101/224493163-d2808ad0-6cc1-47bd-a253-fd6497977aeb.png)

**Comment by jokob-sk** [comment] 2023-03-11 21:09
Hi @pbek !

I really appreciate your quick feedback, helps me a lot! Hope you are well!

This error is odd, never seen this one before.

I [googled around](https://github.com/niklasvh/html2canvas/issues/1741) a bit and this error might be related to a browser extension or browser/browser settings. Could you please try:

1) A different browser?
2) The same browser in private/incognito mode?
3) If the above helps, do you have any privacy extensions? What are they?

With the above, I could try to reproduce the issues on my end and see if it's extension/browser related and could check if there is a workaround or I could at least include in instructions if some are incompatible.

Another thing I came across is that this might be caused by accessing the page via `https://` instead of `http://` as described [here](https://github.com/mqttjs/MQTT.js/issues/1014#issuecomment-565504852) (if I understand this correctly). I never tested PiAlert on SSL so not sure how to even set it up on my end (I'm not too concerned about security on my local network accessible only via a VPN).

Cheers in advance!
j

**Comment by jokob-sk** [comment] 2023-03-11 21:13
I also quickly checked when this code was introduced and it was about 8 months ago:

![image](https://user-images.githubusercontent.com/96159884/224511849-5cdbccb4-a1f2-48cb-a412-f8a93b1015bf.png)

**Comment by pbek** [comment] 2023-03-11 21:29
That's really strange. I have tested it on a machine where I have used pi.alert before. I cannot reproduce the issue on another machine in Firefox and Chrome (although I get some CORS errors in Chrome).

Could have really been a https restriction (I use traefik as ingress proxy with authelia for auth, I never had an issue with it).
And I don't know of browser history restrictions... (there are even more restrictions without https 😁)

So it seems like an false positive, sorry for that! I'll check on the other machine again tomorrow.

**Comment by jokob-sk** [comment] 2023-03-11 21:52
Cool, thanks for the quick update -> will close this for now ;)

**Closed by jokob-sk** 2023-03-11 21:52 UTC
Labels: Waiting for reply

**Comment by pbek** [comment] 2023-03-12 13:31
I found another desktop with the same issue. Both Chrome and Firefox...
Seems like when I use `https://mydomain.com//deviceDetails.php?mac=70:f7:54:7f:23:8c` (got the link in the alert email), instead of `https://mydomain.com/deviceDetails.php?mac=70:f7:54:7f:23:8c` (note that there is only one `/`) I get above error. Chrome is even a bit more verbose with the error messages.

> deviceDetails.php?mac=70%3Af7%3A54%3A7f%3A23%3A8c:1755 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://devicedetails.php/?mac=70%3Af7%3A54%3A7f%3A23%3A8c' cannot be created in a document with origin 'https://mydomain.com' and URL 'https://mydomain//deviceDetails.php?mac=70%3Af7%3A54%3A7f%3A23%3A8c'

**Comment by pbek** [comment] 2023-03-12 13:38
I had set `REPORT_DASHBOARD_URL = 'https://mydomain.com/'`, I'll try `REPORT_DASHBOARD_URL = 'https://mydomain.com'` and wait for the next report mail to see if the uses the correct url now. Maybe it would be good to remove trailing slashes when reading the `REPORT_DASHBOARD_URL` setting?

**Comment by pbek** [comment] 2023-03-14 17:49
Removing the trailing slash in the config solved the issue.

**Comment by jokob-sk** [comment] 2023-03-15 07:22
Thanks for the update - I do have a regex placeholder column in the settings table, but it's low priority right now. I know it's not perfect, but it's in the description for the given setting: 
![image](https://user-images.githubusercontent.com/96159884/225235739-6800ad77-ce3e-478a-a8cd-e4af35029a0c.png)

**Comment by pbek** [comment] 2023-03-15 07:27
The example config also has a trailing slash. 😅 

https://github.com/jokob-sk/Pi.Alert/blob/63a9e55d4edfced4e3f0510a53f975161180fd9e/config/pialert.conf#L26

**Comment by pbek** [comment] 2023-03-15 07:29
I opened https://github.com/jokob-sk/Pi.Alert/pull/198 😉

**Comment by jokob-sk** [comment] 2023-03-15 08:58
Oh missed that, thanks! :)
