### ISSUE TITLE
Timezone not updating properly

### ISSUE THREAD

**Issue by holocronology** [jokob-sk/Pi.Alert#517] opened 2023-12-11 11:21 UTC
I notice my time was wrong and I looked at the help. It indicates that I am set to UTC.

The OS of the LCX reports correct time. I changed the PHP config to the correct timezone per help.

Time remains set at UTC.

**Comment by jokob-sk** [comment] 2023-12-11 21:53
Potentially a duplicate of #509 - should be fixed in the next release or you can check out the `pi.alert_dev` image where the problem should be resolved.

Also, the primary supported installation method is Docker and the CURL/WGET install method is community-only supported. Feel free to contribute via a PR if you know how to fix an issue as well. Please note that the fix should be backward compatible if possible.

**Comment by holocronology** [comment] 2023-12-12 00:49
Sorry, I realize I potentially posted this in the wrong location.  This is related to the Proxmox install. My error.

https://github.com/tteck/Proxmox

**Closed** 2023-12-15 20:48 UTC
Labels: Waiting for reply⏳
