### ISSUE TITLE
Config: Included Sections blank emails

### ISSUE THREAD

**Issue by TomLyon** [jokob-sk/Pi.Alert#113] opened 2022-12-10 15:43 UTC
I've been getting too many event emails so I wanted to disable them entirely. I went into pialert.conf and changed the following line in an attempt to stop event notification emails.

```
#INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events'] # Original Value
INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices']
```

Ever since this change I'm still getting all the event notification emails I was before (I assume, but they're blank) but now even less meaningful as they show up like this:

![Screenshot_20221210_074350](https://user-images.githubusercontent.com/90040568/206863640-83c8a3b0-1c6c-418d-aae0-af80b2b3e980.jpg)

All the emails I was originally getting with event emails are now all blank, with no content.

My workaround for this right now is to just manually disable the Alert All Events box for all my devices, or if you have a lot of devices like I do you can run this command:
```
sudo sqlite3 pialert.db "UPDATE Devices SET dev_AlertEvents = 0;"
```

**Comment by jokob-sk** [comment] 2022-12-11 05:20
Hi!

Thanks for the heads-up!

This should be fixed in the next production image. Related commit:

https://github.com/jokob-sk/Pi.Alert/commit/0f8f3eca81722c0a9945f413706f0b6aec6d2ca4

Closing for now  - will re-open if the issue isn't fixed

**Closed by jokob-sk** 2022-12-11 05:20 UTC
