### ISSUE TITLE
A mismatch of information occurs in the report sent by email

### ISSUE THREAD

**Issue by Walgo** [jokob-sk/Pi.Alert#299] opened 2023-07-30 05:33 UTC
## Describe the issue

Hi, Jokob-sk

A mismatch of information occurs in the report sent by email. Only mac address is on the right place.

Thank's

## Screenshots

![image](https://github.com/jokob-sk/Pi.Alert/assets/137160247/681e25c5-aae8-4b78-a588-e8ed65958548)

**Comment by jokob-sk** [comment] 2023-08-01 20:45
Hi there!

Is this still occurring?

I tested it for a couple of days on my end and I couldn't reproduce the issue:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/33df14c1-5b89-4100-8854-4e8cb9472a0e)

I'll keep this issue open for a couple of days to see if others experience the same issue.

On your end - try checking the HTML generated by the app - there is a file in the `/home/pi/pialert/front/api` mount path called `notification_text.html` which is the email that is sent out by the app. There might be a mismatched `<` or `>` if special characters are used e.g. in device names. 

Thanks,
j

**Comment by sebeksd** [comment] 2023-08-04 05:51
Hi, I have exact same issue, it looks like there is [new line] in date HTML element.

![image](https://github.com/jokob-sk/Pi.Alert/assets/18705953/e2f03aa7-2702-4149-a76e-b08425769ec3)

Fixing this new line manually in html file is enough to fix the table.

![image](https://github.com/jokob-sk/Pi.Alert/assets/18705953/35a4eade-b3b9-4748-9bda-719a0764f125)

My report exported from email (sensitive data replaced with ***):
[Pi.Alert Report.zip](https://github.com/jokob-sk/Pi.Alert/files/12257420/Pi.Alert.Report.zip)

**Comment by Walgo** [comment] 2023-08-05 05:51
Hi Sebeksd

Great ! it is the same problem. it's hard to capture an event that doesn't work. It's irregular.

Thanks !

**Comment by sebeksd** [comment] 2023-08-05 08:11
It is something dependent on environment, for me all of reports are bad. 

All Events reports looks like that:
![image](https://github.com/jokob-sk/Pi.Alert/assets/18705953/35f46e42-d4e3-4a3d-8573-a2eb2e97eece)

And all New device events looks like that:
![image](https://github.com/jokob-sk/Pi.Alert/assets/18705953/0935015e-9fef-4760-b83f-fe533418ef7d)

**Comment by jokob-sk** [comment] 2023-09-10 09:24
Couldn't reproduce (might be fixed in the latest release as well) > Closing for now

**Closed by jokob-sk** 2023-09-10 09:24 UTC
Labels: help-testing
