### ISSUE TITLE
Unable to load network tree

### ISSUE THREAD

**Issue by Maarten-buelens** [jokob-sk/Pi.Alert#353] opened 2023-08-13 15:29 UTC
## Describe the issue

When I open the network tab the network tree does not load. this happens because of a recursion error.

while loading the tree the function getChildren gets called which in turn calls itself for each device.
This leads to too much recursion and it exceeds the call stack.
At the moment I have 51 devices.

##  `pialert.conf` 

```
# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.0.0/24 --interface=ens18']
LOG_LEVEL='debug'
TIMEZONE='Europe/Berlin'
ENABLE_PLUGINS=True
PLUGINS_KEEP_HIST=10000
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD=''
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
REPORT_DASHBOARD_URL='http://pi.alert'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'
UI_PRESENCE=['online','offline','archived']
DAYS_TO_KEEP_EVENTS=90
HRS_TO_KEEP_NEWDEV=0
```

## `docker-compose.yml` 

`docker-compose.yml` 

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped

    volumes:
      - /home/mb/pialert/config:/home/pi/pialert/config
      - /home/mb/pialert/db:/home/pi/pialert/db      
      - /home/mb/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
```

## Screenshots

firefox
![image](https://github.com/jokob-sk/Pi.Alert/assets/69542912/cd1b230c-46b3-4205-af47-a0eb259fb5d8)
chrome
![image](https://github.com/jokob-sk/Pi.Alert/assets/69542912/fa5f191d-6bef-4cb7-8169-4c98b4d644d7)

## Paste last few lines from `pialert.log`

```
Nothing in logs

**Comment by jokob-sk** [comment] 2023-08-13 21:43
Hey 👋,

My guess is that one of the nodes is assigned to itself or a parent node creating a circular reference. Please double-check your assigned parent nodes.

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/0189bf8f-2717-4321-b502-91b7e848bd88)

I'll try to reproduce the behavior on my end an implement at least an error message. 

If needed, you can bulk edit devices via the CSV Export > Edit > CSV Import approach via the Maintenance section. Use an app that doesn't modify line endings if you do (e.g. Notepad ++)

Hope this helps,
j

**Comment by jokob-sk** [comment] 2023-08-14 04:26
Hummm tried to reproduce the behaviour for an hour but couldn't so if you can provide any info on that then that would be great.

You can also send me your devices.csv and I can try to import it on my end (you can anonymize the data of course or email to jokob@duck.com)

**Comment by jokob-sk** [comment] 2023-08-14 04:42
I'll also look into limiting the recursion depth but ideally I would like to find the root cause I guess

**Comment by Maarten-buelens** [comment] 2023-08-14 08:25
If i remove Node from it after I save it it return. So I cannot remove the node from it.

**Comment by jokob-sk** [comment] 2023-08-14 21:16
Can you try to go to the root node in the Devices section and remove everything from this field and save it? 
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/9c9727d8-6541-4099-81ce-4f75f5e5a943)

**Comment by jokob-sk** [comment] 2023-08-14 22:05
If that still doesn't work you can use the CSV approach to modify the values directly:

CSV Export > Edit > CSV Import

**Comment by Maarten-buelens** [comment] 2023-08-20 08:46
when I removed everything from the node field it came back after I saved it.

I tried your latest commit when the node is set to "Internet" I cannot edit it. But the network tree does not work.

Then i did the CSV editing method and that one worked. Thanks

**Comment by jokob-sk** [comment] 2023-08-20 21:22
Glad to hear this worked! I also prevented editing the Root node to prevent misconfiguration so I hope this won't happen to others.

**Comment by jokob-sk** [comment] 2023-09-10 09:20
In release > Closing

**Closed by jokob-sk** 2023-09-10 09:20 UTC
Labels: next release/in dev image
