### ISSUE TITLE
Docker Container Quits After Several Minutes

### ISSUE THREAD

**Issue by ajtatum** [jokob-sk/Pi.Alert#285] opened 2023-07-14 11:37 UTC
## Describe the issue

I start the container and all seems well, but after maybe 10-15 minutes, the container stops. At first I thought it had something to do with the SMTP plugin as it never sends an email, even when Plugins are enabled and REPORT_MAIL is True. I've disabled everything, and it still errors out.

In Portainer, here is a copy of the logs:

```
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
 
06:22:43 Permissions check (All should be True)
06:22:43 ------------------------------------------------
06:22:43   /config/pialert.conf |  READ  | True
06:22:43   /config/pialert.conf |  WRITE | True
06:22:43   /db/pialert.db       |  READ  | True
06:22:43   /db/pialert.db       |  WRITE | True
06:22:43 ------------------------------------------------
06:22:43 [Setup] Attempting to fix permissions.
06:22:43 [Setup] Attempting to fix permissions.
06:22:43 [Database] Opening DB
06:22:43 [upgradeDB] Re-creating Settings table
06:22:43 [upgradeDB] Re-creating Parameters table
06:22:43 [Config] reading config file
06:22:44 [API] Update API starting
06:22:44 [API] Updating table_settings.json file in /front/api
06:22:44 [Config] Imported new config
06:22:44     New version of the container available!
06:22:44 [API] Update API starting
06:22:44 [API] Updating table_devices.json file in /front/api
06:22:44 [API] Updating table_nmap_scan.json file in /front/api
06:22:44 [API] Updating table_pholus_scan.json file in /front/api
06:22:44 [API] Updating table_events_pending_alert.json file in /front/api
06:22:44 [API] Updating table_plugins_events.json file in /front/api
06:22:46 [API] Updating table_plugins_history.json file in /front/api
06:23:24 [API] Updating table_plugins_objects.json file in /front/api
06:23:41 [API] Updating table_language_strings.json file in /front/api
06:23:41 [API] Updating table_custom_endpoint.json file in /front/api
06:23:41 [Internet IP] Check Internet IP started
06:23:41 [Internet IP] - Retrieving Internet IP
06:23:42 [Internet IP] IP:      <IP Removed>
06:23:42 [Internet IP]    Retrieving previous IP:
06:23:42 [Internet IP]      <IP Removed>
06:23:42 [Internet IP]    No changes to perform
06:23:42 [DDNS]     Skipping Dynamic DNS update
06:23:42 [MAIN] cycle:1
06:23:42 [Network Scan] Scan Devices:
06:23:42 [Network Scan] arp-scan start
06:24:16 [Network Scan] arp-scan ends
Killed
```

## Paste your `pialert.conf` (remove personal info)

```
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['<REMOVED>/24 --interface=bond0','<REMOVED>/24 --interface=eth2','<REMOVED>/24 --interface=eth3']
LOG_LEVEL='verbose'
TIMEZONE='America/New_York'
ENABLE_PLUGINS=False
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='<REMOVED>'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=20
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://<REMOVED>:17811'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'

REPORT_MAIL=False
SMTP_SERVER='smtp.mailgun.org'
SMTP_PORT=587
REPORT_TO='<REMOVED>'
REPORT_FROM='<REMOVED>'
SMTP_SKIP_LOGIN=False
SMTP_USER='<REMOVED>'
SMTP_PASS='<REMOVED>'
SMTP_SKIP_TLS=False
SMTP_FORCE_SSL=False

REPORT_WEBHOOK=False
REPORT_APPRISE=False
REPORT_NTFY=False
REPORT_PUSHSAFER=False
REPORT_MQTT=False
DDNS_ACTIVE=False
PIHOLE_ACTIVE=False
DHCP_ACTIVE=False
PHOLUS_ACTIVE=False
NMAP_ACTIVE=False
DHCPLSS_RUN='disabled'
DHCPSRVS_RUN='disabled'
NMAPSRV_RUN='disabled'
SNMPDSC_RUN='disabled'
UNFIMP_RUN='disabled'
WEBMON_RUN='disabled'
```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

`docker-compose.yml` 

```
version: "3.9"
services:
  pi.alert:
    image: jokobsk/pi.alert:latest
    container_name: Pi.Alert
    healthcheck:
      test: curl -f http://<REMOVED>:17811/ || exit 1
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw
      - /volume1/docker/pialert/pihole/pihole-FTL.db:/etc/pihole/pihole-FTL.db:rw
      - /volume1/docker/pialert/pihole/dhcp.leases:/etc/pihole/dhcp.leases:rw
      - /volume1/docker/pialert/api:/home/pi/pialert/front/api:rw
    environment:
      TZ: America/New_York
      PORT: 17811
      HOST_USER_ID: 1026
      HOST_USER_GID: 100
    network_mode: host
    restart: on-failure:5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

`.env` 

Not Applicable

## Screenshots

Not Applicable

## Paste last few lines from `pialert.log`

```
06:22:43 Permissions check (All should be True)
06:22:43 ------------------------------------------------
06:22:43   /config/pialert.conf |  READ  | True
06:22:43   /config/pialert.conf |  WRITE | True
06:22:43   /db/pialert.db       |  READ  | True
06:22:43   /db/pialert.db       |  WRITE | True
06:22:43 ------------------------------------------------
06:22:43 [Setup] Attempting to fix permissions.
06:22:43 [Setup] Attempting to fix permissions.
06:22:43 [Database] Opening DB
06:22:43 [upgradeDB] Re-creating Settings table
06:22:43 [upgradeDB] Re-creating Parameters table
06:22:43 [Config] reading config file
06:22:44 [API] Update API starting
06:22:44 [API] Updating table_settings.json file in /front/api
06:22:44 [Config] Imported new config
06:22:44     New version of the container available!
06:22:44 [API] Update API starting
06:22:44 [API] Updating table_devices.json file in /front/api
06:22:44 [API] Updating table_nmap_scan.json file in /front/api
06:22:44 [API] Updating table_pholus_scan.json file in /front/api
06:22:44 [API] Updating table_events_pending_alert.json file in /front/api
06:22:44 [API] Updating table_plugins_events.json file in /front/api
06:22:46 [API] Updating table_plugins_history.json file in /front/api
06:23:24 [API] Updating table_plugins_objects.json file in /front/api
06:23:41 [API] Updating table_language_strings.json file in /front/api
06:23:41 [API] Updating table_custom_endpoint.json file in /front/api
06:23:41 [Internet IP] Check Internet IP started
06:23:41 [Internet IP] - Retrieving Internet IP
06:23:42 [Internet IP] IP:      <REMOVED>
06:23:42 [Internet IP]    Retrieving previous IP:
06:23:42 [Internet IP]      <REMOVED>
06:23:42 [Internet IP]    No changes to perform
06:23:42 [DDNS]     Skipping Dynamic DNS update
06:23:42 [MAIN] cycle:1
06:23:42 [Network Scan] Scan Devices:
06:23:42 [Network Scan] arp-scan start
06:24:16 [Network Scan] arp-scan ends
06:24:16 [Process Scan]  Processing scan results
06:24:17 [Process Scan] Print Stats
06:24:17 [Scan Stats]    Devices Detected.......: 51
06:24:17 [Scan Stats]        arp-scan detected..: 49
06:24:17 [Scan Stats]        Pi-hole detected...: +0
06:24:17 [Scan Stats]        New Devices........: 0
06:24:17 [Scan Stats]    Devices in this cycle..: 51
06:24:17 [Scan Stats]        Down Alerts........: 0
06:24:17 [Scan Stats]        New Down Alerts....: 0
06:24:17 [Scan Stats]        New Connections....: 2
06:24:17 [Scan Stats]        Disconnections.....: 1
06:24:17 [Scan Stats]        IP Changes.........: 1
06:24:17 [Process Scan] Stats end
06:24:17 [Process Scan] Updating DB Info
06:24:17 [Process Scan] Sessions Events (connect / discconnect)
06:24:17 [Process Scan] Creating new devices
06:24:17 [Process Scan] Updating Devices Info
06:24:17 [Process Scan] Resolve devices names
06:24:17 [Update Device Name] Trying to resolve devices without name
06:24:17 [Update Device Name] Pholus entries from prev scans: 378
06:24:19 [Update Device Name] Names Found (DiG/Pholus): 0 (0/0)
06:24:19 [Update Device Name] Names Not Found         : 21
06:24:19 [Process Scan] Voiding false (ghost) disconnections
06:24:19 [Process Scan] Pairing session events (connection / disconnection) 
06:24:19 [Process Scan] Creating sessions snapshot
06:24:19 [Process Scan] Inserting scan results into Online_History
06:24:19 [Process Scan] Skipping repeated notifications
06:24:19 [Skip Repeated Notifications] Skip Repeated start
06:24:19 [Skip Repeated Notifications] Skip Repeated end
06:24:19 [Notification] Check if something to report
06:24:19 [Notification] Open text Template
06:24:19 [Notification] Open html Template
06:24:19 [Notification] included sections: ['internet', 'new_devices', 'down_devices', 'events']
06:24:19 [Notification] Internet sections done.
06:24:19 [Notification] New Devices sections done.
06:24:19 [Notification] Down Devices sections done.
06:24:19 [Notification] Events sections done.
06:24:19 [Notification] Changes detected, sending reports
06:24:19 [Notification] Udateing API files
06:24:19 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
06:24:19 [Notification] Skip email
06:24:19 [Notification] Skip Apprise
06:24:19 [Notification] Skip webhook
06:24:19 [Notification] Skip NTFY
06:24:19 [Notification] Skip PUSHSAFER
06:24:19 [Notification] Skip MQTT
06:24:19 [Notification] Notifications changes: 0
06:24:19 [MAIN] cycle:cleanup
06:24:19 [DB Cleanup] Upkeep Database:
06:24:19 [DB Cleanup] Online_History: Delete all but keep latest 150 entries
06:24:19 [DB Cleanup] Optimize Database
06:24:19 [DB Cleanup] Events: Delete all older than 90 days
06:24:19 [DB Cleanup] Plugin Events History: Delete all older than 90 days
06:24:19 [DB Cleanup] Pholus_Scan: Delete all older than 7 days
06:24:19 [DB Cleanup] Pholus_Scan: Delete all duplicates
06:24:19     Nmap_Scan: Delete all duplicates
06:24:19     Shrink Database
06:24:30 [MAIN] Last action: cleanup
06:24:30 [MAIN] cycle:
06:24:30 [MAIN] Process: Wait
06:24:35 [API] Update API starting
06:24:35 [API] Updating table_devices.json file in /front/api
```

## Additional Notes
I followed the instructions from [Marius Hosting](https://mariushosting.com/how-to-install-pi-alert-on-your-synology-nas/) to have it on my Synology NAS. The networks are actually VLANs, but I couldn't get them to work and since I have the extra ports on my Synology I just ran a cable to the switches.

**Comment by ajtatum** [comment] 2023-07-14 11:48
I just noticed something that's interesting, for my NAS it shows as "Online" but the First Session and the Last Session are the same, 2023-05-20 17:50. Shouldn't the last session be current, especially since the device is online? It appears this way for numerous devices... where the last session isn't showing an updated value.

**Comment by ajtatum** [comment] 2023-07-14 11:50
By the way, my router is OPNsense.

**Comment by jokob-sk** [comment] 2023-07-14 21:11
Hi @ajtatum !

Appreciate the detailed description!

Can you enable the debug and follow the instructions here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

Ideally, we'd like to get an error message before the container crashes. 

Thanks in advance 🙏
j

**Comment by ajtatum** [comment] 2023-07-16 16:45
So, it does seem that there was an issue earlier when I had SMTP turned on and it would error out. However, I have that turned off (hopefully temporairly) so that's not an issue.

I changed the container to only stop unless-stopped, and there are periods where it becomes unresponsive and then comes back online. During this short period, I noticed on the app there was something about "mkdir: /run/php already exists" or something; however, that's not in the logs anywhere even with debug tuned on. Perhaps it errors out right after that and doesn't "officially" right it to the logs?

Either way, because there's a lot of sensitivity, I have the file zipped and at https://drive.google.com/file/d/1JusRIgNAdwRoRxxEC_9KSunXNFWSvJg4/view?usp=sharing. The password is "pialert". Once you've downloaded it, please let me know and I'll remove it from my drive.

Thanks,
AJ

**Comment by ajtatum** [comment] 2023-07-16 16:47
Also to add, just by looking at the log and timestamps, this thing is very busy.... I do have several networks and a lot of devices, so perhaps it needs more resources? Or is it normal to be as active as it is?

**Comment by ajtatum** [comment] 2023-07-16 17:29
Here it is:

13:28:15 [Database] - get_table_as_json - Query: SELECT  * FROM Nmap_Scan
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.

**Comment by jokob-sk** [comment] 2023-07-16 21:07
Hi there,

I downloaded the file, feel free to delete it.

Will have a look at it later.

If there is no error (the one you mentioned is expected behaviour), try starting the container via the terminal without the "-d" parameter, so when it quits a complete error message is logged in the terminal.

Thanks,
J

**Comment by ajtatum** [comment] 2023-07-16 23:27
Thanks. I have it as a Stack in Portainer and, while I'm aware of how to compose up/down in the CLI, I've always done it for things not created in Portainer. So I'll have to see how about I can do that. It's really odd and does seem like it's doing a TON of processing (possible the ARP Scan) and then stops for a few seconds and moves onto something else rather quickly. After what seems to be perhaps doing one of the networks, if I'm navigating around, the app will just not respond and I'll be given the Chrome error page and then within a few seconds the app is back up and running. I don't know why it errored out while trying to send an email, I was using Mailgun and typically don't have any problems there.

Anyway, I truly appreciate you digging into this and researching it. For me, it's providing to be an invaluable resource to see the network and keep track of devices. I've just sponsored the project through my business ([AJ Tatum Digital](https://github.com/AJTatumDigital)). Wish I could do more!

**Comment by jokob-sk** [comment] 2023-07-17 21:54
Hi there!

Thanks for the support, in any kind or form :) 

```
     [API] Updating table_pholus_scan.json file in /front/api
     [API] Updating table_events_pending_alert.json file in /front/api
     [API] Updating table_plugins_history.json file in /front/api
     [API] Updating table_custom_endpoint.json file in /front/api
    Changes detected, sending reports
      Sending report by Email

 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
```

Looks like the container restarts just after attempting to send an email. This might mean the email settings are not configured correctly. 

Try enabling `debug` as described here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

This should give you more details about what exactly the code fails on. Usually, it's an SSL misconfiguration of the SSL connection. If using GMAIL as SMTP check this as well: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SMTP_GMAIL.md

Hope this helps,
j

**Comment by ajtatum** [comment] 2023-07-18 11:43
Well, you were right about the SSL connection. I use Mailgun and tried using ports 587 and 465 and neither worked, but port 25 worked. Odd though that caused it to error out despite it being disabled. However, I received an onslaught of emails back to back, almost non-stop, so I disabled the Email setting again. The emails were for devices that were connected or disconnected, but I know that most of the devices reported as disconnected were most definitely connected as otherwise my WiFi would have been down.

Any ideas as to why Pi.Alert would think a device is disconnected? That's one main feature that I'd like to be notified on.

Also, in the emails and in the logs, it keeps claiming that a new version is available, but I'm running the latest, at least according to the footer which shows "Built on: 2023-06-15" and that lines up with your [latest release](https://github.com/jokob-sk/Pi.Alert/releases).

Thanks for your help!
AJ

**Comment by jokob-sk** [comment] 2023-07-18 21:37
Hi there!

Glad to hear there's progress!

Can you please check if the container restarts? Repeated notifications might mean that the notification queue wasn't cleared before the restart so on the next cycle they are sent out again.

Please post the last few lines of the pialert.log file just before a  restart or ideally when the container crashes in the terminal as described here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

Online/Offline states are reported via arp-scan or, if enabled, via PiHole. If these report a device as offline, is it marked offline. 

There is a bug in the version check, that should be  addressed in the next release: #283 

Hope this helps!
j

**Comment by jokob-sk** [comment] 2023-07-24 20:51
No activity for a while > closing for now. Will reopen if needed

**Closed by jokob-sk** 2023-07-24 20:51 UTC
Labels: Waiting for reply

**Comment by jokob-sk** [comment] 2023-09-18 12:52
For anyone reading. GMX as smtp server config guide added here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SMTP.md
