### ISSUE TITLE
Web UI not available and docker ps shows no portt for the container

### ISSUE THREAD

**Issue by andreizet66** [jokob-sk/Pi.Alert#558] opened 2024-02-07 12:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

Kindly asking for help in setting up pi.alert as a docker container since my raspberry pi died on me after 2 years. Web UI is not accessible and docker ps shows no port. From the logs, it seems like the container my be in a loop, but I can't for the life of me figure out why. Initially I thought I need to wait for the scan to finish, as the github readme mentions, but it's been 1 hour and webui is still not accessible. Thanks in advance for all the help and I'm honestly sorry if I'm missing anything obvious. 

**DOCKER PS:**

CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                             PORTS           NAMES
f35ff7345e93   jokobsk/pi.alert:latest   "/home/pi/pialert/do…"   26 minutes ago   Up 26 minutes                                    pialert

### Expected Behavior

Container starts, shows port and web ui is accessible.

### Steps To Reproduce

docker compose up -d
access http://<<mi-ip>>: 20211

### pialert.conf

```python
andreizet@ubuntu-legion:~/Documents/pi.alert$ cd config
andreizet@ubuntu-legion:~/Documents/pi.alert/config$ sudo nano pialert.conf

  GNU nano 6.2                                                               pialert.conf                                                                         
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2022-12-30_22-19-40            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
# Scan using interface eth0
# SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0']
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1']

TIMEZONE='Europe/<<CITY>>'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
DAYS_TO_KEEP_EVENTS=90
                                                                        [ Read 98 lines ]
```

### docker-compose.yml

```python
GNU nano 6.2                                                                compose.yml                                                                         
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    volumes:
      - /home/andreizet/Documents/pi.alert/config:/home/pi/pialert/config
      - /home/andreizet/Documents/pi.alert/db:/home/pi/pialert/db
      # (optional) useful for debugging if you have issues setting up the container
      - /home/andreizet/Documents/pi.alert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/<<CITY>>
      - HOST_USER_ID=0
      - HOST_USER_GID=0 #running as root to check if permissions are an issue
      - PORT=20211
```

### What branch are you running?

Production

### pialert.log

.txt file with docker logs pialert uploaded because of character number limitation. 

[pialert_logs.txt](https://github.com/jokob-sk/Pi.Alert/files/14193770/pialert_logs.txt)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by daniel-alomar** [comment] 2024-02-07 20:10
Do you have a firewall? Have you already open the 20211/TCP port?

**Comment by jokob-sk** [comment] 2024-02-07 20:47
Hi @andreizet66 ,

Can you post a screenshot of what you are getting when accessing `HTTP://<your rpi IP>/20211`?

In my Portainer instance, this is how the network looks on my end:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c1a25b07-0de5-4547-a475-ad1a23667c29)

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/7dc64844-8c6b-43a5-8934-68df1a06c932)

You can always ssh into the container and have a look if nginx is running, but even if it isn't I assume you should be able to access `HTTP://<your rpi IP>/20211`.

Here is the `top` output inside of the running container (notice `nginx` in the list):

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/7c6b2f09-120d-4912-ac53-ea0101a48b51)

Can you also run the following in the container to see the processes and their ports?

`sudo apt-get install lsof`

`sudo lsof -i`

The above should show something like this:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/880d4281-8c89-49ac-83af-5a8b5e5a196b)


- Do you have any other app running on the `20211` port by any chance?

Thanks in advance for the details,
j

**Comment by andreizet66** [comment] 2024-02-08 15:15
> Do you have a firewall? Have you already open the 20211/TCP port?

I do have ufw installed (I'm on Ubuntu 22.04 LTS). I did sudo ufw allow 20211. Here's the confirmation. 

```
andreizet@ubuntu-legion:~/Documents/pialert$ sudo ufw allow 20211
[sudo] password for andreizet: 
Skipping adding existing rule
Skipping adding existing rule (v6)

```

**Comment by andreizet66** [comment] 2024-02-08 15:17
@jokob-sk 

It seems that the problem is even deeper. I cant even SSH into the container. When trying to acquire container IP with 

`docker inspect -f "{{ .NetworkSettings.IPAddress }}" <<container-id>>`

command returns nothing. 

I'm a little bit in over my head here. What is nginx supposed to do for pi.alert? I have nginx proxy manager installed, but I use it for domains and all thet. 

Thank you all for replying and trying to help.

**Comment by andreizet66** [comment] 2024-02-08 23:51
It is clearly an issue on my side since it works for anyone else. At this point you're just so nice to help me. 

Here's what I found/tried until now, after also taking a look at the resources in your reply. 

1. Reconfirmed port 20211 is not used by anything else. Just to be sure, I tried using port 29999. Results are identical. 
```
andreizet@ubuntu:~/Documents/pialert$ netstat -an | grep 20211 #returns nothing
andreizet@ubuntu:~/Documents/pialert$ sudo lsof -i :20211 #returns nothing
```

2. Changed restart policy in docker compose to `restart: no` to make sure that the container is not in a restart loop. It isn't, the container does not stop. 

4. Tried using docker run (provided on [Docker instructions](https://github.com/jokob-sk/Pi.Alert/blob/main/dockerfiles/README.md) page. Results are identical. 

5. Switched to a simpler docker compose file with absolute paths. Results are identical.

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: no
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db
      - ./logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/<<CITY>>
      - PORT=20211
```

7. Since my ubuntu laptop is connected to wifi for the moment, I edited the interface in the pialert.conf file to the value below. Results are...identical. 

`SCAN_SUBNETS=['192.168.1.0/24 --interface=wlp0s20f3']`

**Question:** Is it normal to see `[MAIN] waiting to start next loop` so often (check logs below)? 

**Logs:** for everything I did: 
[pialert_docker_log_andreizet.txt](https://github.com/jokob-sk/Pi.Alert/files/14215707/pialert_docker_log_andreizet.txt)

**Screenshot** of what I see when trying to access the UI: 
![firefox](https://github.com/jokob-sk/Pi.Alert/assets/65792896/435c64b7-57ca-4343-90e8-395594a34e42)

**Screenshot** of Docker desktop still not displaying a port: 
![docker desktop](https://github.com/jokob-sk/Pi.Alert/assets/65792896/b0eb7f5d-d729-4e49-9e70-361df6c8f89e)

**Comment by jokob-sk** [comment] 2024-02-09 09:14
Hey @andreizet66 ,

There is usually a way to open a terminal in Docker desktop, not sure if the UI is the same as the picture I've found: 

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/a846e5b8-0cb3-40e9-b15e-efb3a19520f7)

I myself don't use Docker desktop so not 100% sure where to look. 

> Question: Is it normal to see [MAIN] waiting to start next loop so often (check logs below)?

Yes, that's completely normal. 

Also, can you please check if Docker desktop on Ubuntu supports host network?

```yaml
network_mode: "host"
```

I am not sure if it does so please double-check. I know it does NOT on the Windows version of Docker desktop.

**Comment by andreizet66** [comment] 2024-02-09 10:06
According to [the official Docker documentation](https://docs.docker.com/network/drivers/host/#:~:text=The%20host%20networking%20driver%20only,the%20docker%20service%20create%20command.): 

#_The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server._

The "Open in terminal" button exists, but the UI in your picture is an old one. You now have to click on the container as you would to show logs and then click on the three-dots button under the container name or click "view details" and go to "exec" tab. 

I ran the following commands mentioned in your previous reply: 

```
top
sudo apt-get install lsof
sudo lsof -i
```

Seems like...nothing is wrong??

Please see command line output below:

```
**top** - 11:56:08 up 14:23,  0 user,  load average: 0.34, 0.19, 0.15
Tasks:  20 total,   1 running,  19 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.9 us,  0.3 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.1 st 
MiB Mem :   2662.9 total,    215.8 free,   2325.2 used,    563.7 buff/cache     
MiB Swap:   1024.0 total,    257.8 free,    766.2 used.    337.7 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                              
    1 root      20   0    3924   2432   2304 S   0.0   0.1   0:00.01 bash                                                                                                 
  128 root      20   0  213548   3976   2560 S   0.0   0.1   0:00.01 php-fpm8.2                                                                                           
  129 www-data  20   0  213548   3352   1920 S   0.0   0.1   0:00.00 php-fpm8.2                                                                                           
  130 www-data  20   0  213548   3352   1920 S   0.0   0.1   0:00.00 php-fpm8.2                                                                                           
  141 root      20   0   99776   2944    512 S   0.0   0.1   0:00.00 nginx                                                                                                
  142 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  143 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  144 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  145 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  146 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  147 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  148 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  149 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  150 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  151 www-data  20   0  100108   4096   1408 S   0.0   0.2   0:00.00 nginx                                                                                                
  152 root      20   0  116956  37428  12544 S   0.0   1.4   0:02.70 python                                                                                               
  153 www-data  20   0  100108   3968   1280 S   0.0   0.1   0:00.00 nginx                                                                                                
  154 www-data  20   0  100108   3968   1280 S   0.0   0.1   0:00.00 nginx                                                                                                
  296 root      20   0    2576   1408   1408 S   0.0   0.1   0:00.00 sh                                                                                                   
  409 root      20   0    8640   4864   2816 R   0.0   0.2   0:00.02 top                                                                                                  



**# sudo apt-get install lsof**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  lsof
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 318 kB of archives.
After this operation, 494 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 lsof amd64 4.95.0-1 [318 kB]
Fetched 318 kB in 0s (1013 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
Selecting previously unselected package lsof.
(Reading database ... 30720 files and directories currently installed.)
Preparing to unpack .../lsof_4.95.0-1_amd64.deb ...
Unpacking lsof (4.95.0-1) ...
Setting up lsof (4.95.0-1) ...

**# sudo lsof -i**             
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
nginx   141 root    5u  IPv4 1722879      0t0  TCP *:20211 (LISTEN)
# 
```

**Comment by rcjcarr** [comment] 2024-02-09 13:59
I have the same problem on a Raspberry Pi 4; no ports, no WEB UI:
```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS
                           NAMES
694d88ed506f   jokobsk/pi.alert:latest   "/home/pi/pialert/do…"   5 minutes ago    Up 12 seconds
                           pialert
e49bf57ee63c   selfhostedpro/yacht       "/init"                  28 minutes ago   Up 28 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   yacht
```
docker-compose yml file is:
```yml
version: "3"
services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db/pialert.db
      # (optional) useful for debugging if you have issues setting up the container
      - ./logs:/home/pi/pialert/front/log
    environment:
      - TZ=America/Toronto
      - PORT=20211
```

Container is continuously restarting. Logs show:
```txt
) (1.16.0)
[INSTALL] Setup NGINX
Removing existing PiAlert web-UI
Removing existing PiAlert NGINX config
Setting webserver to user-supplied port (20211)
[INSTALL] Run the hardware vendors update
The file ieee-oui.txt exists. Skipping update_vendors.sh...
[INSTALL] Fixing file permissions
[INSTALL] Fixing WEB_UI_DIR: /var/www/html/pialert
[INSTALL] Fixing INSTALL_DIR: /home/pi
[INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
[INSTALL] Fixing permissions after copied starter config & DB
Starting nginx: nginx.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/pialert/pialert/__main__.py", line 75, in main
    db.upgradeDB()
  File "/home/pi/pialert/pialert/database.py", line 85, in upgradeDB
    onlineHistoryAvailable = self.sql.execute("""
                             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'execute'
08:58:56 [MAIN] Setting up ...
08:58:56 [conf.tz] Setting up ...
08:58:56

08:58:56 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
08:58:56

08:58:56 Permissions check (All should be True)
08:58:56 ------------------------------------------------
08:58:56   /config/pialert.conf |  READ  | True
08:58:56   /config/pialert.conf |  WRITE | True
08:58:56   /db/pialert.db       |  READ  | True
08:58:56   /db/pialert.db       |  WRITE | True
08:58:56 ------------------------------------------------
08:58:56 [Setup] Attempting to fix permissions.
08:58:56 [Setup] Attempting to fix permissions.
08:58:56 [Database] Opening DB
08:58:56 [Database] - Open DB Error: unable to open database file
```

**Comment by rcjcarr** [comment] 2024-02-09 14:16
Issuing this command did not change anything:
```bash
docker exec pialert chown -R www-data:www-data /home/pi/pialert/db/pialert.db
```

**Comment by rcjcarr** [comment] 2024-02-09 14:23
Complete log file:
```txt
rc@pi-alert:~/appdata/pialert $ docker logs -f pialert
---------------------------------------------------------
[INSTALL]                                    Run start.sh
---------------------------------------------------------
[INSTALL] Run setup scripts
---------------------------------------------------------
[INSTALL]                             Run user-mapping.sh
---------------------------------------------------------
USER_ID  : 1000
USER_GID : 992
USER_HOME:
TZ       : America/Toronto
chown: missing operand after '1000:992 '
Try 'chown --help' for more information.
---------------------------------------------------------
[INSTALL]                     Run install_dependencies.sh
---------------------------------------------------------
Reading package lists...
Building dependency tree...
Reading state information...
tini is already the newest version (0.19.0-1).
snmp is already the newest version (5.9.3+dfsg-2).
ca-certificates is already the newest version (20230311).
curl is already the newest version (7.88.1-10+deb12u5).
libwww-perl is already the newest version (6.68-1).
arp-scan is already the newest version (1.10.0-2).
perl is already the newest version (5.36.0-7+deb12u1).
apt-utils is already the newest version (2.6.1).
cron is already the newest version (3.0pl1-162).
sudo is already the newest version (1.9.13p3-1+deb12u1).
nginx-light is already the newest version (1.22.1-9).
php is already the newest version (2:8.2+93).
php-cgi is already the newest version (2:8.2+93).
php-fpm is already the newest version (2:8.2+93).
php-sqlite3 is already the newest version (2:8.2+93).
php-curl is already the newest version (2:8.2+93).
sqlite3 is already the newest version (3.40.1-2).
dnsutils is already the newest version (1:9.18.19-1~deb12u1).
net-tools is already the newest version (2.10-0.1).
python3 is already the newest version (3.11.2-1+b1).
iproute2 is already the newest version (6.1.0-3).
nmap is already the newest version (7.93+dfsg1-1).
python3-pip is already the newest version (23.0.1+dfsg-1).
zip is already the newest version (3.0-13).
systemctl is already the newest version (1.4.4181-1.1).
usbutils is already the newest version (1:014-1).
traceroute is already the newest version (1:2.1.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
nginx is already the newest version (1.22.1-9).
nginx-core is already the newest version (1.22.1-9).
mtr is already the newest version (0.95-1).
php-fpm is already the newest version (2:8.2+93).
php8.2-fpm is already the newest version (8.2.7-1~deb12u1).
php-cli is already the newest version (2:8.2+93).
php8.2 is already the newest version (8.2.7-1~deb12u1).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
python3.11-venv is already the newest version (3.11.2-6).
python3.11-venv set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /myenv/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: paho-mqtt in /myenv/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: scapy in /myenv/lib/python3.11/site-packages (2.5.0)
Requirement already satisfied: cron-converter in /myenv/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: pytz in /myenv/lib/python3.11/site-packages (2023.3.post1)
Requirement already satisfied: json2table in /myenv/lib/python3.11/site-packages (1.1.5)
Requirement already satisfied: dhcp-leases in /myenv/lib/python3.11/site-packages (0.1.6)
Requirement already satisfied: pyunifi in /myenv/lib/python3.11/site-packages (2.21)
Requirement already satisfied: speedtest-cli in /myenv/lib/python3.11/site-packages (2.1.3)
Requirement already satisfied: chardet in /myenv/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /myenv/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /myenv/lib/python3.11/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /myenv/lib/python3.11/site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /myenv/lib/python3.11/site-packages (from requests) (2023.11.17)
Requirement already satisfied: python-dateutil in /myenv/lib/python3.11/site-packages (from cron-converter) (2.8.2)
Requirement already satisfied: six>=1.5 in /myenv/lib/python3.11/site-packages (from python-dateutil->cron-converter) (1.16.0)
[INSTALL] Setup NGINX
Disabling default NGINX site, removing sym-link in /etc/nginx/sites-enabled
Setting webserver to user-supplied port (20211)
[INSTALL] Run the hardware vendors update
The file ieee-oui.txt exists. Skipping update_vendors.sh...
[INSTALL] Fixing file permissions
[INSTALL] Fixing WEB_UI_DIR: /var/www/html/pialert
[INSTALL] Fixing INSTALL_DIR: /home/pi
[INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
[INSTALL] Fixing permissions after copied starter config & DB
Starting nginx: nginx.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/pialert/pialert/__main__.py", line 75, in main
    db.upgradeDB()
  File "/home/pi/pialert/pialert/database.py", line 85, in upgradeDB
    onlineHistoryAvailable = self.sql.execute("""
                             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'execute'
09:22:52 [MAIN] Setting up ...
09:22:52 [conf.tz] Setting up ...
09:22:52

09:22:52 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
09:22:52

09:22:52 Permissions check (All should be True)
09:22:52 ------------------------------------------------
09:22:52   /config/pialert.conf |  READ  | True
09:22:52   /config/pialert.conf |  WRITE | True
09:22:52   /db/pialert.db       |  READ  | True
09:22:52   /db/pialert.db       |  WRITE | True
09:22:52 ------------------------------------------------
09:22:52 [Setup] Attempting to fix permissions.
09:22:52 [Setup] Attempting to fix permissions.
09:22:52 [Database] Opening DB
09:22:52 [Database] - Open DB Error: unable to open database file
```

**Comment by andreizet66** [comment] 2024-02-09 14:48
Update: Installed an Ubuntu 22.04 LTS VM via Gnome Boxes and configured Docker Engine (i.e. without Docker Desktop). Ran pi.alert container with the run command from the docker instructions here on github. Everything works fine.

Coult it be that it cannot be run on Docker Desktop? If that's the case, I'd have to redo 90% of all my configuration just to install pi.alert.

**Comment by rcjcarr** [comment] 2024-02-09 16:25
False alarm for me... :( Problem was yml file. Changed
FROM:
```yml
  - ./db:/home/pi/pialert/db/pialert.db
 ```
TO
```yml
  - ./db:/home/pi/pialert/db
 ```
and all problems went away.

**Comment by jokob-sk** [comment] 2024-02-09 20:18
Hi @andreizet66 ,

Glad to hear it's working. 

The issue is probably what you discovered earlier:

> #The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

This means that Docker Desktop on Linux doesn't support `network_mode: "host"`. Regrettably that's something which is required to run PiAlert. An alternative is to either:

1. Install on HW directly (Experimental and only community supported): https://github.com/jokob-sk/Pi.Alert/blob/main/docs/HW_INSTALL.md
2. Try to get PiAlert working without `network_mode: "host"`. This is something I tried before but couldn't get working so any help is appreciated. 

You can also look at this as an opportunity to re-do your setup, but I understand if that's something you don't want to do.

Thanks,
j

**Comment by jokob-sk** [comment] 2024-02-09 20:30
Closing this as the root cause issue was identified - please open a separate issue if needed.

**Comment by andreizet66** [comment] 2024-02-09 20:31
I appreciate the time you invested in looking into this. Thank you! 

I'll most likely re-do my setup. I started with Docker desktop to get comfortable with containers and never really grew out of it, but I guess it's time. Especially since I can get Portainer and manage everything through there. 

No reason to keep the issue open, since the conclusion is that this is a Docker issue and not a Pi.Alert issue.

**Closed by jokob-sk** 2024-02-09 20:30 UTC
Labels: Setup 📥

**Comment by jokob-sk** [comment] 2024-02-09 23:29
Good luck! Consider supporting me 😅
Have a great weekend,
j
