### ISSUE TITLE
Pi.Alert shows fqdn with no dot separators e.g. "hostdomaincom" instead of "host.domain.com"

### ISSUE THREAD

**Issue by harr2969** [jokob-sk/Pi.Alert#165] opened 2023-02-03 19:58 UTC
I've got pi.alert learning via pi.hole, nmap and pholus.

About 35 of my ~40 devices on the home network are showing as "hostdomaincom" instead of "host.domain.com"

If I look in my pi.hole docker (for example "top 10 clients") they show correctly with "host.domain.com"

Any suggestions on how I can determine where this is breaking and what's the most effective way to fix it?

See docker run and other info on [issue 164](https://github.com/jokob-sk/Pi.Alert/issues/164), and .conf excerpt below.

18:35:44 root@nas:/volume1/docker/pialert/config# cat pialert.conf

# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1']
PRINT_LOG=False
TIMEZONE='Europe/London'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert/'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'

# PiHole
#---------------------------
PIHOLE_ACTIVE=True
DHCP_ACTIVE=True

# Pholus
#---------------------------
PHOLUS_ACTIVE=True
PHOLUS_TIMEOUT=20
PHOLUS_FORCE=False
PHOLUS_RUN='schedule'
PHOLUS_RUN_TIMEOUT=600
PHOLUS_RUN_SCHD='0 4 * * *'
PHOLUS_DAYS_DATA=7

# Nmap
#---------------------------
NMAP_ACTIVE=True
NMAP_TIMEOUT=150
NMAP_RUN='none'
NMAP_RUN_SCHD='0 2 * * *'
NMAP_ARGS='-p -10000'

## EXCLUDED DISABLED SECTIONS ##

**Comment by jokob-sk** [comment] 2023-02-03 23:54
I think I've found the issue. Can you try deploying this dev build to see if the issue is fixed?

DockerHub image tag is:

`jokobsk/pi.alert_dev:sha-b5f0a64`

**Comment by harr2969** [comment] 2023-02-05 23:00
Ok, trying, thanks.

**Comment by harr2969** [comment] 2023-02-05 23:31
Restarting with the existing DB didn't seem to resolve the issue, but clearing the hosts from the maint menu and letting it reload did. Thanks!

**Comment by jokob-sk** [comment] 2023-02-05 23:34
Cool, closing 😉

**Closed by jokob-sk** 2023-02-05 23:34 UTC
Labels: Waiting for reply

**Comment by harr2969** [comment] 2023-02-06 05:44
NP - will this be merged back into the main branch in future? (How long should I keep running the fork?)

**Comment by jokob-sk** [comment] 2023-02-06 06:26
yes, will be fixed in the next release

**Comment by killtux** [comment] 2023-03-11 12:26
cool to see the new release fixed it. but now devices show up with dot between domain & hostname.... and one additional after the domain 😅

![image](https://user-images.githubusercontent.com/36768145/224484348-18bf2563-2331-401b-bc15-89f7ca105aa4.png)

**Comment by jokob-sk** [comment] 2023-03-11 12:40
What would you expect the default behaviour to do?

**Comment by killtux** [comment] 2023-03-11 19:10
normally its "host.domain" without a second dot at the end i think?

**Comment by jokob-sk** [comment] 2023-03-11 20:33
Cool, understood, should be fixed with https://github.com/jokob-sk/Pi.Alert/commit/6dd1448667d769e69c293b9fc7d16dd36ba5b2e7
