### ISSUE TITLE
Device type dropdown doesn't work on device details page

### ISSUE THREAD

**Issue by jasonehines** [jokob-sk/Pi.Alert#500] opened 2023-11-10 22:37 UTC
On the device details page, when I click the dropdown I get just a small white bar where the list of items should be.

I looked through the code and couldn't find the problem. I tested the sql query that's used to do the lookup and got the expected results.

my config and docker files are the same as in issue #496 

log (debug is on and this is all there was after I visited the page)

```

17:33:04 [Import Config] checking config file 
17:33:04 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:04 [Import Config] fileModifiedTime         :1699654878.431957
17:33:04 [Import Config] skipping config file import
17:33:04 [API] Update API starting
17:33:04 [MAIN] waiting to start next loop
17:33:09 [Import Config] checking config file 
17:33:09 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:09 [Import Config] fileModifiedTime         :1699654878.431957
17:33:09 [Import Config] skipping config file import
17:33:09 [API] Update API starting
17:33:09 [MAIN] waiting to start next loop
17:33:14 [Import Config] checking config file 
17:33:14 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:14 [Import Config] fileModifiedTime         :1699654878.431957
17:33:14 [Import Config] skipping config file import
17:33:14 [API] Update API starting
17:33:14 [MAIN] waiting to start next loop
17:33:19 [Import Config] checking config file 
17:33:19 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:19 [Import Config] fileModifiedTime         :1699654878.431957
17:33:19 [Import Config] skipping config file import
17:33:19 [API] Update API starting
17:33:19 [MAIN] waiting to start next loop
17:33:24 [Import Config] checking config file 
17:33:24 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:24 [Import Config] fileModifiedTime         :1699654878.431957
17:33:24 [Import Config] skipping config file import
17:33:24 [API] Update API starting
17:33:25 [MAIN] waiting to start next loop
17:33:30 [Import Config] checking config file 
17:33:30 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:30 [Import Config] fileModifiedTime         :1699654878.431957
17:33:30 [Import Config] skipping config file import
17:33:30 [API] Update API starting
17:33:30 [MAIN] waiting to start next loop
17:33:35 [Import Config] checking config file 
17:33:35 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:35 [Import Config] fileModifiedTime         :1699654878.431957
17:33:35 [Import Config] skipping config file import
17:33:35 [API] Update API starting
17:33:35 [MAIN] waiting to start next loop
17:33:40 [Import Config] checking config file 
17:33:40 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:40 [Import Config] fileModifiedTime         :1699654878.431957
17:33:40 [Import Config] skipping config file import
17:33:40 [API] Update API starting
17:33:40 [MAIN] waiting to start next loop
17:33:45 [Import Config] checking config file 
17:33:45 [Import Config] lastImportedConfFile     :1699654878.431957
17:33:45 [Import Config] fileModifiedTime         :1699654878.431957
17:33:45 [Import Config] skipping config file import
17:33:45 [API] Update API starting
17:33:45 [MAIN] waiting to start next loop
                              
```

**Comment by jokob-sk** [comment] 2023-11-10 22:49
Hi @jasonehines ,

I think this is a duplicate of this issue fixed in the dev image: https://github.com/jokob-sk/Pi.Alert/issues/483

**Comment by jasonehines** [comment] 2023-11-10 23:30
It does look like the same issue, totally missed it.

Where is the dev repo?

**Comment by jokob-sk** [comment] 2023-11-11 01:14
Thanks for checking. Here is the image name:

```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert_dev"
    network_mode: "host"
    restart: always
    volumes:
      - ${APP_DATA_LOCATION}/pialert_dev/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION}/pialert_dev/db:/home/pi/pialert/db
      - ${LOGS_LOCATION}/:/home/pi/pialert/log
    environment:
      - TZ=Europe/Berlin
      - HOST_USER_ID=1036
      - HOST_USER_GID=1000
      - PORT=20211
```

**Comment by jokob-sk** [comment] 2023-11-11 01:15
Duplicate

**Closed by jokob-sk** 2023-11-11 01:15 UTC
Labels: Waiting for reply⏳
