### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by ukdanmc** [jokob-sk/Pi.Alert#189] opened 2023-02-25 22:40 UTC
Hi,

I need help getting this working with docker-compose. I am receiving a popup error when on the devices page.

"DataTables warning: table id=tableDevices - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

Below is my docker compose file.

Many thanks for any help.

version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /docker/pialert/config:/home/pi/pialert/config
      - /docker/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      - /docker/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/London
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211

**Comment by jokob-sk** [comment] 2023-02-25 22:47
Hi,

This error might be caused by RW permissions missing. Try mapping a folder instead of a DB file directly to initialize an empty DB.

Also, please post the required info to help you to debug the issue as per the issue template. This saves us both time to go back and forth.

Issue format for reference: 

**Describe the issue**


**Paste last few lines from `pialert.log`**

```

paste here

```

**Paste your `pialert.conf` (remove personal info)**

```

paste here

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 
```

paste here

```


`.env` 
```

paste here

```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by ukdanmc** [comment] 2023-02-27 15:44
Hi, thanks for you reply. I originally mapped the DB folder and then changed it to the file after reading common issues.
Logs below. 

PiAlert.log
[2023-02-27 15:36:23] Scan: Pholus for 600s (10.0min)
        Pholus scan on [interface] enp1s0 [mask] 192.168.1.0/24
[2023-02-27 15:36:55] Scan: Pholus SUCCESS
[2023-02-27 15:36:23] Scan Devices:
    arp-scan start
  Processing scan results
    Devices Detected.......: 48
        arp-scan detected..: 46
        Pi-hole detected...: +0
        New Devices........: 0
    Devices in this cycle..: 48
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 1
        Disconnections.....: 3
        IP Changes.........: 0
  Updating DB Info
    Sessions Events (connect / discconnect)
    Creating new devices
    Updating Devices Info
        Trying to resolve devices without name
          Pholus entries from prev scans: 94000
        Names Found (DiG/Pholus): 0 (0/0)
        Names Not Found         : 26
    Voiding false (ghost) disconnections
    Pairing session events (connection / disconnection) 
    Creating sessions snapshot
    Inserting scan results into Online_History
    Skipping repeated notifications
[2023-02-27 15:37:11] Scan: Nmap for max 150s (2.5min) per device
        Estimated max delay: 7800s (130.0min)
[2023-02-27 15:37:36] Scan: Nmap SUCCESS for 192.168.1.1 (1/52)
[2023-02-27 15:37:36] Scan: Nmap found 5 new or changed ports

pialert.log
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2022-12-30_22-19-40            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
# Scan using interface eth0
# SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0']
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]
SCAN_SUBNETS=['192.168.1.0/24 --interface=enp1s0']
PRINT_LOG=False
TIMEZONE='Europe/London'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD=
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert/'


Docker Compose File
version: "3"
services:
pialert:
container_name: pialert
image: "jokobsk/pi.alert:latest"
network_mode: "host"
restart: unless-stopped
volumes:
- /docker/pialert/config:/home/pi/pialert/config
- /docker/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
- /docker/pialert/logs:/home/pi/pialert/front/log
environment:
- TZ=Europe/London
- HOST_USER_ID=1000
- HOST_USER_GID=1000
- PORT=20211

Screenshot of the error
![Screenshot 2023-02-27 154352](https://user-images.githubusercontent.com/28921745/221610266-b7c619f0-acf9-4325-86f4-d9ea13cc2751.png)

**Comment by jokob-sk** [comment] 2023-02-27 23:06
Hi,

Thanks for the info.

Could you please post the result of the back end response by following these steps:

1) open developer console in your browser (usually, e. g for Chrome, key F12 on the keyboard)
2) follow the steps in this screenshot: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/img/DEBUG/Invalid_JSON_repsonse_debug.png
3) Post the response or error in this thread.

Thanks,
J

**Comment by ukdanmc** [comment] 2023-02-28 08:15
Hi,

Just tried but get nothing in the response section. See screenshot below.


<img width="1219" alt="Screenshot 2023-02-28 at 08 12 27" src="https://user-images.githubusercontent.com/28921745/221793263-633f9b28-a786-4099-bfd7-2df0eb1c9847.png">

**Comment by jokob-sk** [comment] 2023-02-28 20:29
Thanks for that. The response is empty,which is odd. Are you sure the DB permissions are set correctly? E. G. Are the group and user is you've set here correct?

HOST_USER_ID=1000
HOST_USER_GID=1000

Is the container restarting and if yes what are the last few lines in the log file before and after the restart?

**Comment by ukdanmc** [comment] 2023-03-02 09:06
Hi,

Permissions match a user and group that I use for other containers, so pretty sure it isn't that. 
The container isn't restarting but just sits at starting nginx.

[+] Running 1/0
 ⠿ Container pialert  Created                                                                                     0.0s
Attaching to pialert
pialert  | Starting nginx: nginx

**Comment by jokob-sk** [comment] 2023-03-03 21:52
Alright, let's investigate further.

1) I've noticed you have an error in your console. Could you please provide more information on what the error details are:

![image](https://user-images.githubusercontent.com/96159884/222834576-284bee07-c5a6-41b1-9ecb-9b6612b3053c.png)

2) Can you show me the response of both queries in your screenshot?

![image](https://user-images.githubusercontent.com/96159884/222835170-3b41c734-1126-4cf5-bc6b-a6b9928425dc.png)

It looks like that your device totals are not populated so maybe that's the call that fails.

Can you try entering the following URLs in the address bar of your browser directly and post the redacted results?

- `http://<pialert URL>:20211/php/server/devices.php?action=getDevicesTotals`
- `http://<pialert URL>:20211/php/server/devices.php?action=getDevicesList&status=all`

The results should look something like this:

First URL:

![image](https://user-images.githubusercontent.com/96159884/222836017-dc0c1f86-fcb8-4aa1-ae30-7b21f3ac00c4.png)

Second URL:

![image](https://user-images.githubusercontent.com/96159884/222836280-6645035a-2446-45c0-8f6d-9b307e095d2f.png)

For the second URL, please copy and paste the result into an online JSON checker, such as [this one](https://jsonchecker.com/) to check if it's valid.

**Comment by ukdanmc** [comment] 2023-03-04 05:46
As requested, please find screenshots. Second URL and second repsonse produce nothing.

<img width="996" alt="Screenshot 2023-03-04 at 05 37 19" src="https://user-images.githubusercontent.com/28921745/222878138-ff17378b-cafe-4d0b-909a-60724e3646c5.png">
<img width="996" alt="Screenshot 202
<img width="996" alt="Screenshot 2023-03-04 at 05 40 41" src="https://user-images.githubusercontent.com/28921745/222878214-d2e81b46-385d-41a9-83d8-1304fbeb4d57.png">
<img width="996" alt="Screenshot 2023-03-04 at 05 40 31" src="https://user-images.githubusercontent.com/28921745/222878215-7ccb8398-5d57-4ea6-85ff-f5c07613d817.png">
<img width="996" alt="Screenshot 2023-03-04 at 05 37 54" src="https://user-images.githubusercontent.com/28921745/222878136-6d36cd44-20e7-41de-9ea0-54d269117e51.png">
<img width="996" alt="Screenshot 2023-03-04 at 05 38 08" src="https://user-images.githubusercontent.com/28921745/222878299-9331d3a1-d639-4040-bb3b-f5b4187632dc.png">

**Comment by jokob-sk** [comment] 2023-03-04 08:44
Thanks for that. It's odd there is no response, not even an error. 

![image](https://user-images.githubusercontent.com/96159884/222886028-88d50b7a-cf0b-46d7-b161-24ad841c89a4.png)

- Can you go to Maintenance and save the order of the columns?
- If the above doesn't help, can you try to access `http://<pialert URL>:20211/php/server/devices.php?action=getDevicesList&status=all&forceDefaultOrder`?
- Can you post the last few lines of the `pialert_front.log` file?

**Comment by jokob-sk** [comment] 2023-03-12 08:41
poster didn't reply for a week > closing for now

**Closed by jokob-sk** 2023-03-12 08:41 UTC
Labels: Waiting for reply
