### ISSUE TITLE
v23.9.11 Unexpected reboot 

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#435] opened 2023-09-12 09:50 UTC
Built on: 2023-09-12 | Version: v23.9.11
Unexpected reboot after Update (last Hotfix, Issue #420).

It seem that  it comes from the DHCPLSS Module. If DHCPLSS is activated, the Server is rebooting after reading and analyzing the lease file. If deactivated, the server is up and running without problems.

![Bildschirmfoto 2023-09-12 um 11 23 21](https://github.com/jokob-sk/Pi.Alert/assets/22064392/b526a889-76dd-4389-9087-4d343ee59e25)

**Comment by ace16vitamine** [comment] 2023-09-12 09:58
@jokob-sk, this problem WAS NOT while ive tested the dev image as discussed in Issue 
#420

**Comment by jokob-sk** [comment] 2023-09-12 10:07
Hi!

I haven't touched the plugin since you tested it so unsure where the issue is. Can you share your DHCP.leases file(s) you are using? 

Thanks in advance,
j

**Comment by ace16vitamine** [comment] 2023-09-12 10:33
Hi @jokob-sk 

best way is to forward the lease file. Can you give me your mail address pls? To prevent spam, send it to ot23@agibo.de , I will answer and forward the file

**Comment by jokob-sk** [comment] 2023-09-12 11:13
You can mail me at jokob@duck.com

**Comment by ace16vitamine** [comment] 2023-09-12 11:27
done

**Comment by jokob-sk** [comment] 2023-09-12 21:18
Hi @ace16vitamine 

Thanks for the dcp.leases file. I tested it on the latest dev build and it seems to be working fine:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c11c234e-d362-4a80-bc9f-5b05402e2e4d)


 Could you please try to re-download the dev image and try again?
 
 You can also try to run the command directly in the container and check the `cat /home/pi/pialert/front/plugins/dhcp_leases/last_result.log` file:

`python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths=path1,path2`

Thanks for the patience!
j

**Comment by ace16vitamine** [comment] 2023-09-13 00:32
Hi,

yes, on dev it is working. But not on the latest stable version (Built on: 2023-09-12 | Version: v23.9.11)

**Comment by jokob-sk** [comment] 2023-09-13 02:38
The latest stable is 23.9.12 can you check?

**Comment by jokob-sk** [comment] 2023-09-13 02:49
Also, thanks a lot for the quick feedback, appreciated 🙏 it's impossible to test all use cases just by myself 😅

**Comment by jokob-sk** [comment] 2023-09-14 12:29
seems to be working > closing

**Closed by jokob-sk** 2023-09-14 12:29 UTC
Labels: Waiting for reply
