### ISSUE TITLE
Multiple Alerts

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#445] opened 2023-09-14 09:14 UTC
Built on: 2023-09-13 | Version: Dev

Hi,

today I found a device, discovered with the pihole sync.

It seems that the device Name is correct (picture 1), in Details same are missing (picture 2) and the Emails are coming with multiple alerts (Picture 3) without Device Name. It seems that the sync with pihole is not correct.

![Bildschirmfoto 2023-09-14 um 11 10 50](https://github.com/jokob-sk/Pi.Alert/assets/22064392/2b048aa5-bcdb-42ea-a8c2-da5d8998ac58)

![Bildschirmfoto 2023-09-14 um 11 11 03](https://github.com/jokob-sk/Pi.Alert/assets/22064392/6992de18-f06f-4053-a009-06a6d88a0c51)

![Bildschirmfoto 2023-09-14 um 11 11 15](https://github.com/jokob-sk/Pi.Alert/assets/22064392/728fd0ef-5f58-4f22-9025-b56a26415236)

**Comment by jokob-sk** [comment] 2023-09-14 10:16
Hi there!

A few possible causes:

1. If you have multiple scan methods enabled they will produce duplicate entries in the CurrentScan table. The app doesn't perform de-duplication on that table.
2. If you use multiple scan methods, the Vendor entries and Names might come from different plugins. 
3. The "*" looks like it may come from your `dhcp.leases` file.

Try disabling and running only one plugin for device discovery.

Thanks,
j

**Comment by ace16vitamine** [comment] 2023-09-14 12:38
I've now disabled other detections, but the alert with pinhole detection is again multiple ![image](https://github.com/jokob-sk/Pi.Alert/assets/22064392/1ed93906-2c11-42bd-aae3-d88cb923d897)

**Comment by jokob-sk** [comment] 2023-09-14 22:03
Thanks for the details!

Hummm, I can't seem to reproduce this error.

Here is the state of my test DB:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c88edd79-9f9f-4388-8865-13a0a38bca8a)

This results in this email:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/acb52cef-f420-4a89-89f6-3ada017321c5)

I have only the PIHOLE plugin enabled, nothing else. 

At this point, the only thing I can do is test the app on your PIHOLE DB if you like me to, or youc an run the same queries on your end and post the results. 

Thanks,
j

**Comment by ace16vitamine** [comment] 2023-09-14 22:24
Hm, I have this error after deleting the PIHOLE_CMD. After that (in dev) I have this issue.

**Comment by jokob-sk** [comment] 2023-09-15 08:25
This is the value of PIHOLE_CMD taht is returning these results:

```
SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote};
```

this is then resolved into this SQL query:

```
SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, 'null' AS Extra, n.hwaddr AS ForeignKey FROM Network AS n LEFT JOIN Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE 'ip-%' AND n.hwaddr <> '00:00:00:00:00:00';
```

You can try to run that on the PIHOLE DB

**Comment by jokob-sk** [comment] 2023-09-15 10:17
hummm, should I do  "top 1" to select only one entry per mac or leave it be to capture the multiple IP addresses (I assume the are in the PLugins_History table view for the PIHOLE plugin - can you have a look?

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/07da8875-e9b8-4bb9-ab72-ff110a67a2d5)

What do you think?

**Comment by jokob-sk** [comment] 2023-09-15 10:34
Hey!

If that's the SQL you want to use try using this value in your settings:

```
SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote} GROUP BY n.hwaddr;
```

could you please also answer my previous question?

> leave it be to capture the multiple IP addresses (I assume the are in the PLugins_History table view for the PIHOLE plugin - can you have a look?

Thanks,
j

**Comment by jokob-sk** [comment] 2023-09-20 10:08
closing as no activity - will reopen if needed

**Closed by jokob-sk** 2023-09-20 10:08 UTC
Labels: Waiting for reply
